spring.application.name=myfirstwebapp

#for jsp/view
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#for logs
logging.level.org.springframework=info
logging.level.com.in28minutes.springboot.myfirstwebapp=debug

spring.mvc.format.date=yyyy-MM-dd


#setting up mysql database via docker
spring.datasource.url=jdbc:mysql://localhost:3306/todos
spring.datasource.username=todos-user
spring.datasource.password=dummytodos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update




#Launch MySQL using Docker------------------------
#docker run --detach 
#--env MYSQL_ROOT_PASSWORD=dummypassword 
#--env MYSQL_USER=todos-user 
#--env MYSQL_PASSWORD=dummytodos 
#--env MYSQL_DATABASE=todos 
#--name mysql 
#--publish 3306:3306 
#mysql:8-oracle
#


#application.properties----------------------------
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/todos
#spring.datasource.username=todos-user
#spring.datasource.password=dummytodos
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



#mysqlsh commands-----------------------------------
#mysqlsh
#\connect todos-user@localhost:3306  then enter password(i.e. dummytodos)
#\sql
#use todos
#select * from todo;
#\quit