spring.application.name=restful-web-services
#logging.level.org.springframework=debug
management.endpoints.web.exposure.include=*

#spring.jpa.show-sql=true

spring.security.user.name=username
spring.security.user.password=password


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true


#Docker for Todos
#docker run --detach 
#--env MYSQL_ROOT_PASSWORD=dummypassword 
#--env MYSQL_USER=todos-user 
#--env MYSQL_PASSWORD=dummytodos 
#--env MYSQL_DATABASE=todos 
#--name mysql 
#--publish 3306:3306 
#mysql:8-oracle




#for connecting with docker for social-media   
#docker run --detach 
#--env MYSQL_ROOT_PASSWORD=dummypassword 
#--env MYSQL_USER=social-media-user 
#--env MYSQL_PASSWORD=dummypassword 
#--env MYSQL_DATABASE=social-media-database 
#--name mysql 
#--publish 3306:3306 
#mysql:8-oracle




#/src/main/resources/application.properties Modified
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://localhost:3306/social-media-database
#spring.datasource.username=social-media-user
#spring.datasource.password=dummypassword
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect




#
#mysqlsh commands
#mysqlsh
#\connect social-media-user@localhost:3306
#\sql
#use social-media-database
#select * from user_details;
#select * from post;
#\quit




